# Generated by Django 6.1 on 2026-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdetails",
            name="foundDate",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemdetails",
            name="location",
            field=models.TextField(default="ktm", max_length=300),
        ),
        migrations.AddField(
            model_name="itemdetails",
            name="phoneNo",
            field=models.CharField(default="98989898", max_length=20),
        ),
        migrations.AlterField(
            model_name="itemdetails",
            name="itemTag",
            field=models.TextField(blank=True, default="electronic", null=True),
        ),
    ]
