# Generated by Django 6.1 on 2026-09-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_itemdetails_founddate_itemdetails_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemdetails",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Found Item",
                "verbose_name_plural": "Found Items",
            },
        ),
        migrations.AlterField(
            model_name="itemdetails",
            name="foundDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="itemdetails",
            name="itemTag",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("wallet", "Wallet / Purse"),
                    ("bag", "Bag / Backpack"),
                    ("keys", "Keys"),
                    ("document", "Documents / ID"),
                    ("jewelry", "Jewelry"),
                    ("clothing", "Clothing"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="itemdetails",
            name="location",
            field=models.CharField(default="Kathmandu", max_length=300),
        ),
        migrations.AlterField(
            model_name="itemdetails",
            name="phoneNo",
            field=models.CharField(default="98000000", max_length=20),
        ),
    ]
